-- Application storage. Run in the same Supabase project as the SweetProcess import.
BEGIN;
CREATE TABLE IF NOT EXISTS public.kb_spaces (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL UNIQUE,
 icon text NOT NULL DEFAULT 'folder'
);
CREATE TABLE IF NOT EXISTS public.kb_users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL,
 email text NOT NULL UNIQUE,
 password text NOT NULL,
 role text NOT NULL CHECK (role IN ('admin','reader')),
 folder_ids bigint[] NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS public.kb_documents (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title text NOT NULL,
 body text NOT NULL,
 space_id bigint NOT NULL REFERENCES public.kb_spaces(id),
 status text NOT NULL CHECK (status IN ('published','draft')),
 author_id bigint NOT NULL REFERENCES public.kb_users(id),
 updated timestamptz NOT NULL DEFAULT now(),
 source_type text,
 source_id bigint,
 UNIQUE (source_type, source_id)
);
CREATE INDEX IF NOT EXISTS kb_documents_folder_status ON public.kb_documents(space_id,status);
-- department_folders:<id> stores a JSON folder ID array.
-- department_access:<user-id> stores {department_ids: [...], folder_ids: [...]}.
-- Both grant lists are replaced atomically; kb_users.folder_ids is legacy input
-- only until a department_access record exists. No department grant means no access.
CREATE TABLE IF NOT EXISTS public.kb_settings (key text PRIMARY KEY,value text NOT NULL);
CREATE TABLE IF NOT EXISTS public.kb_sessions (
 token_hash text PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES public.kb_users(id) ON DELETE CASCADE,
 expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS kb_sessions_expiry ON public.kb_sessions(expires_at);

ALTER TABLE public.kb_spaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kb_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kb_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kb_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kb_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.kb_spaces, public.kb_users, public.kb_documents, public.kb_settings, public.kb_sessions FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kb_spaces, public.kb_users, public.kb_documents, public.kb_settings, public.kb_sessions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.kb_spaces_id_seq, public.kb_users_id_seq, public.kb_documents_id_seq TO service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
